###
# this is a *runner-only, independent* configuration. It should not be used
# with demo.yaml. This is for when you host tinyci off-k8s.
---
apiVersion: v1
kind: Secret
metadata:
  name: tinyci-config
type: Opaque
stringData:
  runner.yaml: |-
    queue: "default"
    namespace: "runs"
    max_concurrency: 5
    clients:
      queuesvc: "10.0.0.50:6001"
      assetsvc: "10.0.0.50:6002"
      logsvc: "10.0.0.50:6005"
      tls:
        ca: /etc/tinyci.crt/ca.crt
        cert: /etc/tinyci.crt/client.crt
        key: /etc/tinyci.crt/client.key
---
apiVersion: v1
kind: Namespace
metadata:
  name: runs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: run-jobs
rules:
  - apiGroups: ["objects.tinyci.org"]
    resources: ["cijobs"]
    verbs: ["create", "delete", "update", "get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-runner
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: run-jobs-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: run-jobs
subjects:
  - kind: ServiceAccount
    namespace: default
    name: k8s-runner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  labels:
    app: tinyci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyci
  template:
    metadata:
      labels:
        app: tinyci
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: runner
          image: tinyci/runners:latest
          command: ["k8s-runner", "-c", "/etc/tinyci/runner.yaml"]
          volumeMounts:
            - name: config
              mountPath: "/etc/tinyci"
              readOnly: true
            - name: certs
              mountPath: "/etc/tinyci.crt"
              readOnly: true
      serviceAccountName: k8s-runner
      volumes:
        - name: config
          secret:
            secretName: tinyci-config
        - name: certs
          secret:
            secretName: tinyci-certs
